import type { Metadata } from "next";
import { Cal_Sans } from "next/font/google";
import "@/styles/globals.css";
import { LocaleProvider } from "@/context/LocaleProvider";

const cal_sans = Cal_Sans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cal_sans.className} antialiased`}>
        <LocaleProvider>{children}</LocaleProvider>
      </body>
    </html>
  );
}
